services:
  siif-rest1:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
 
    networks:
      - siif-network
    environment:
      - PORT=3000
      - LOCALUSER=${USER}

networks:
  siif-network:
    name: siif-network
